/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelForm;


import Entitas.EditMobil;
import Entitas.TambahMobil;
import Implements.ImCrudMobil;
import Koneksi.koneksi;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.xml.bind.DatatypeConverter.parseInt;
import static javax.xml.bind.DatatypeConverter.parseInteger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import validasi.validasi;


/**
 *
 * @author lenovo
 */
public class AddCar extends javax.swing.JPanel {
      Connection kon = new koneksi().BukaKon();
      public DefaultTableModel tabModel;
      validasi val = new validasi();
      String tamp;
      int id;
      
    /**
     * Creates new form AddCar
     */
    public AddCar() {
        initComponents();
        this.addContainerListener(null);
        tablemobil.setModel(new ImCrudMobil().tampil());
        btnTambah.setEnabled(true);
      
    }
    
    
    
    public void reset(){
        
        mrk.setText("");
        tipe.setText("");
        thn.setSelectedItem("");
        NoPol.setText("");
        Harga.setText("");
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablemobil = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mrk = new javax.swing.JTextField();
        tipe = new javax.swing.JTextField();
        thn = new javax.swing.JComboBox<>();
        NoPol = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        dataCari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        tablemobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tablemobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemobilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablemobil);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Merek Mobil");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tipe Mobil");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Tahun Produksi");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("No Polisi");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Harga Sewa");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Status");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Data Mobil");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        mrk.setBackground(new java.awt.Color(51, 51, 51));
        mrk.setForeground(new java.awt.Color(255, 255, 255));
        mrk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mrkKeyPressed(evt);
            }
        });
        jPanel3.add(mrk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 250, -1));

        tipe.setBackground(new java.awt.Color(51, 51, 51));
        tipe.setForeground(new java.awt.Color(255, 255, 255));
        tipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipeKeyPressed(evt);
            }
        });
        jPanel3.add(tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, -1));

        thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel3.add(thn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, -1));

        NoPol.setBackground(new java.awt.Color(51, 51, 51));
        NoPol.setForeground(new java.awt.Color(255, 255, 255));
        NoPol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoPolKeyPressed(evt);
            }
        });
        jPanel3.add(NoPol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Keluar" }));
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, -1));

        jLabel15.setText(":");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 10, 20));

        jLabel16.setText(":");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 10, 20));

        jLabel17.setText(":");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 10, 20));

        jLabel18.setText(":");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 10, 20));

        jLabel19.setText(":");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 10, 20));

        jLabel20.setText(":");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 10, 20));

        Harga.setBackground(new java.awt.Color(51, 51, 51));
        Harga.setForeground(new java.awt.Color(255, 255, 255));
        Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HargaKeyPressed(evt);
            }
        });
        jPanel3.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 250, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0,180));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset2.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 390, 30));

        dataCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCariActionPerformed(evt);
            }
        });

        cari.setBackground(new java.awt.Color(0, 0, 0,180));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        cari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cariFocusLost(evt);
            }
        });
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 204, 255,95));
        jLabel22.setText("jarvis");

        jLabel23.setFont(new java.awt.Font("Consolas", 3, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255,200));
        jLabel23.setText("Car Rental");

        jButton7.setBackground(new java.awt.Color(0, 0, 0,180));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus2.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0,180));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        jButton6.setText("Update");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 0, 0,180));
        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tambah.png"))); // NOI18N
        btnTambah.setText("Add");
        btnTambah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mobilLogo.jpg"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0,180));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_archive_white_18dp.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0,180));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/RESET.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(dataCari, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel23))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dataCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here
        String merek = mrk.getText();
        String tp = tipe.getText();
        String tahun =(String) thn.getSelectedItem();
        String no = NoPol.getText();
        int hrg = parseInt(Harga.getText());
        String sts = (String) status.getSelectedItem();
        TambahMobil tbh = new TambahMobil(merek,tp,tahun,no,hrg,sts);
        ImCrudMobil save = new ImCrudMobil();
         if(mrk.getText().equals("")||tipe.getText().equals("")||NoPol.getText().equals("")||Harga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Benar!!!");
            mrk.requestFocus();
        }else{
            try {
              save.simpan(tbh);
              tablemobil.setModel(new ImCrudMobil().tampil());
              reset();
            } catch (Exception ex) {
              Logger.getLogger(AddCar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
          
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tablemobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemobilMouseClicked
        // TODO add your handling code here:
         int baris = tablemobil.rowAtPoint(evt.getPoint());
         tamp = tablemobil.getValueAt(baris, 0).toString();
         id=parseInt(tamp);
         mrk.setText(tablemobil.getValueAt(baris, 1).toString());
         tipe.setText(tablemobil.getValueAt(baris, 2).toString());
         thn.setSelectedItem(tablemobil.getValueAt(baris, 3).toString());
         NoPol.setText(tablemobil.getValueAt(baris, 4).toString());
         Harga.setText(tablemobil.getValueAt(baris, 5).toString());
         status.setSelectedItem(tablemobil.getValueAt(baris, 6).toString());
         btnTambah.setEnabled(false);
    }//GEN-LAST:event_tablemobilMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(mrk.getText().equals("")||tipe.getText().equals("")||NoPol.getText().equals("")||Harga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Benar!!!");
            mrk.requestFocus();
        }else{
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want to Edit Data?","Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
                try {
                    String merek = mrk.getText();
                    String tp = tipe.getText();
                    String tahun =(String) thn.getSelectedItem();
                    String no = NoPol.getText();
                    int hrg = parseInt(Harga.getText());
                    String sts = (String) status.getSelectedItem();
                    EditMobil ubah = new EditMobil(id,merek,tp,tahun,no,hrg,sts);
                    ImCrudMobil save = new ImCrudMobil();
                    save.edit(ubah);
                    tablemobil.setModel(new ImCrudMobil().tampil());
                    reset();
                    btnTambah.setEnabled(true);
                } catch (Exception ex) {
                    Logger.getLogger(AddCar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }reset();
        }  
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
              ImCrudMobil save = new ImCrudMobil();
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete Data?","Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
             try {
              save.hapus(id);
              tablemobil.setModel(new ImCrudMobil().tampil());
              btnTambah.setEnabled(true);
            } catch (Exception ex) {
              Logger.getLogger(AddCar.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }      
        reset();   
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        ImCrudMobil save = new ImCrudMobil();
        String data = dataCari.getText();
        tablemobil.setModel(save.cari(data));
        reset();
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_cariActionPerformed

    private void mrkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mrkKeyPressed
        char karakter = evt.getKeyChar();
        String nama = mrk.getText();
        int panjangnama = nama.length();
        if (val.valNama(karakter, panjangnama)==false){
            mrk.setEditable(false);
        }else{
            if(val.valNamaBatas(karakter, panjangnama)==true){
                mrk.setEditable(true);
                if(panjangnama>=0&&panjangnama<35){
                    if(panjangnama==30){
                        mrk.setEditable(false);
                    }
                }
                mrk.setEditable(true);
            }else{
                mrk.setEditable(false);
            }
        }
    }//GEN-LAST:event_mrkKeyPressed

    private void tipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipeKeyPressed
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        String nama = tipe.getText();
        int panjangnama = nama.length();
        if (val.valNama(karakter, panjangnama)==false){
            tipe.setEditable(false);
        }else{
            if(val.valNamaBatas(karakter, panjangnama)==true){
                tipe.setEditable(true);
                if(panjangnama>=0&&panjangnama<35){
                    if(panjangnama==30){
                        tipe.setEditable(false);
                    }
                }
                tipe.setEditable(true);
            }else{
                tipe.setEditable(false);
            }
        }
    }//GEN-LAST:event_tipeKeyPressed

    private void HargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaKeyPressed
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        String noNik = Harga.getText();
        int panjangNik = noNik.length();
        if (val.valNik(karakter, panjangNik)==false) {
            Harga.setEditable(false);
        }else{
            if(val.valbatas(karakter, panjangNik)==true){
                Harga.setEditable(true);
                if(panjangNik>=0&&panjangNik<=10){
                    if(panjangNik>10){
                        Harga.setEditable(false);
                    }
                }

            }else{
                Harga.setEditable(false);
            }

        }
    }//GEN-LAST:event_HargaKeyPressed

    private void NoPolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoPolKeyPressed
        char karakter = evt.getKeyChar();
        String plat = NoPol.getText();
        int panjangplat = plat.length();
        
        if(val.valplat(karakter, panjangplat)==true){
            NoPol.setEditable(true);
        }else{
            NoPol.setEditable(false);
        }
        
    }//GEN-LAST:event_NoPolKeyPressed
   private void notah() throws JRException{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String report="C:\\Users\\lenovo\\Documents\\NetBeansProjects\\RentalMobil\\src\\Laporan\\DataMobil.jrxml";
            JasperReport jreport = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jreport,null, kon);
            JasperViewer.viewReport(jp);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(peminjam.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    private void dataCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cariFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cariFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         tablemobil.setModel(new ImCrudMobil().tampil());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {
              // TODO add your handling code here:
              notah();
          } catch (JRException ex) {
              Logger.getLogger(AddCar.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField NoPol;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton cari;
    private javax.swing.JTextField dataCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mrk;
    private javax.swing.JComboBox<String> status;
    public javax.swing.JTable tablemobil;
    private javax.swing.JComboBox<String> thn;
    private javax.swing.JTextField tipe;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
